# Generated by Django 4.2.4 on 2023-08-15 19:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app_tienda', '0004_alter_categoria_producto_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='color_producto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'colorProd',
                'verbose_name_plural': 'colorsProd',
            },
        ),
        migrations.CreateModel(
            name='talla_producto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'tallaProd',
                'verbose_name_plural': 'tallasProd',
            },
        ),
        migrations.AddField(
            model_name='producto',
            name='color',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='app_tienda.color_producto'),
        ),
        migrations.AddField(
            model_name='producto',
            name='talla',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='app_tienda.talla_producto'),
        ),
    ]
