# Generated by Django 4.2.4 on 2023-08-15 20:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_tienda', '0006_producto_descripcin'),
    ]

    operations = [
        migrations.RenameField(
            model_name='producto',
            old_name='descripcin',
            new_name='descripcion',
        ),
    ]
