# Generated by Django 4.2.4 on 2023-08-15 20:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_tienda', '0007_rename_descripcin_producto_descripcion'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='producto',
            name='color',
        ),
        migrations.RemoveField(
            model_name='producto',
            name='talla',
        ),
        migrations.DeleteModel(
            name='color_producto',
        ),
        migrations.DeleteModel(
            name='talla_producto',
        ),
    ]
