# Generated by Django 4.2.4 on 2023-08-15 20:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_tienda', '0008_remove_producto_color_remove_producto_talla_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='producto',
            name='disponible',
        ),
    ]
