# Generated by Django 4.2.4 on 2023-08-16 14:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_tienda', '0009_remove_producto_disponible'),
    ]

    operations = [
        migrations.RenameField(
            model_name='producto',
            old_name='imagen',
            new_name='imagen_1',
        ),
        migrations.AddField(
            model_name='producto',
            name='imagen_2',
            field=models.ImageField(blank=True, null=True, upload_to='tienda'),
        ),
        migrations.AddField(
            model_name='producto',
            name='imagen_3',
            field=models.ImageField(blank=True, null=True, upload_to='tienda'),
        ),
        migrations.AddField(
            model_name='producto',
            name='imagen_4',
            field=models.ImageField(blank=True, null=True, upload_to='tienda'),
        ),
    ]
