# Generated by Django 4.2.4 on 2023-08-25 14:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_tienda', '0011_remove_producto_imagen_2_remove_producto_imagen_3_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='producto',
            old_name='imagen_1',
            new_name='imagen',
        ),
    ]
